export const CHANGE_TIMER_STEPS = 'CHANGE_TIMER_STEPS';

export const CHANGE_RECIPE = 'CHANGE_RECIPE';

export const REQUEST_RECIPESLIST_PENDING = 'REQUEST_RECIPESLIST_PENDING';
export const REQUEST_RECIPESLIST_SUCCESS = 'REQUEST_RECIPESLIST_SUCCESS';
export const REQUEST_RECIPESLIST_FAILED = 'REQUEST_RECIPESLIST_FAILED';

export const REQUEST_RECIPE_BY_ID_PENDING = 'REQUEST_RECIPE_BY_ID_PENDING';
export const REQUEST_RECIPE_BY_ID_SUCCESS = 'REQUEST_RECIPE_BY_ID_SUCCESS';
export const REQUEST_RECIPE_BY_ID_FAILED = 'REQUEST_RECIPE_BY_ID_FAILED';

export const REQUEST_RECIPES_BY_TAG_PENDING = 'REQUEST_RECIPES_BY_TAG_PENDING';
export const REQUEST_RECIPES_BY_TAG_SUCCESS = 'REQUEST_RECIPES_BY_TAG_SUCCESS';
export const REQUEST_RECIPES_BY_TAG_FAILED = 'REQUEST_RECIPES_BY_TAG_FAILED'; 